Bump org.jetbrains.kotlin:kotlin-gradle-plugin from 2.3.0 to 2.3.10 (#34)
Bumps
[org.jetbrains.kotlin:kotlin-gradle-plugin](https://github.com/JetBrains/kotlin)
from 2.3.0 to 2.3.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin:kotlin-gradle-plugin's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 2.3.10-RC2</h2>
<h2>ChangeLog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83984"><code>KT-83984</code></a>
Data races around kotlinx.serialization plugin protobuf extensions
registration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83983"><code>KT-83983</code></a>
Revert of KT-83081</li>
</ul>
<h2>Kotlin 2.3.10-RC</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83314"><code>KT-83314</code></a>
JSpecify <code>@NullMarked</code> changes Java equals(Object) to
equals(Any?) causing override conflict in Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83317"><code>KT-83317</code></a>
ClassCastException: with cast kotlin.UInt to java.lang.Number when
defining constant</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83031"><code>KT-83031</code></a>
K2: unstable resolution of EnhancedNullability from type-use NotNull in
presence of unused code</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82863"><code>KT-82863</code></a>
<code>@NoInfer</code> regression since 2.2.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82841"><code>KT-82841</code></a>
&quot;kotlin.NoWhenBranchMatchedException&quot; in <code>when</code>
with <code>!is</code> check &amp; non-sealed class in the middle of
hierarchy</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://issuetracker.google.com/issues/195200551"><code>b/195200551</code></a>
Fix classId for detecting protobuf enums</li>
<li><a
href="https://issuetracker.google.com/issues/463961757"><code>b/463961757</code></a>
Simplify Compose group analysis</li>
<li><a
href="https://issuetracker.google.com/issues/463961757"><code>b/463961757</code></a>
Fix analysis of boolean captures in composable lambda</li>
<li><a
href="https://issuetracker.google.com/issues/461766771"><code>b/461766771</code></a>
Fix <code>IrSimpleFunction.isLegacyOpenFunctionWithDefault</code></li>
</ul>
<h3>JVM. Reflection</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83608"><code>KT-83608</code></a>
Kotlin-reflect: &quot;Unknown origin of public abstract operator fun
invoke(p1: P1, p2: P2): R&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-42199"><code>KT-42199</code></a>
&quot;KotlinReflectionInternalError: Unknown origin of public abstract
operator fun invoke&quot; on function reference to FunctionN.invoke</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-81024"><code>KT-81024</code></a>
Reflection: New KType implementation fails on arguments comparison for a
Nothing type parameter</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83361"><code>KT-83361</code></a>
&quot;KotlinReflectionInternalError: Type parameter not found: 0&quot;
on super types with Kotlin 2.3.0</li>
</ul>
<h3>Tools. Compiler Plugins</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83266"><code>KT-83266</code></a>
&quot;Unsupported class file major version 69&quot; for
&quot;produceReleaseComposeMapping&quot; task with Kotlin 2.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83099"><code>KT-83099</code></a>
Compose compiler does not generate stack trace mappings for project
files</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83070"><code>KT-83070</code></a>
The KGP api reference is missing a description</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82459"><code>KT-82459</code></a>
Improve iOS simulator boot implementation</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82946"><code>KT-82946</code></a>
Js, Wasm: Upgrade NPM dependencies</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83687"><code>KT-83687</code></a>
Revert deprecation of 'androidTarget' for AGP lower than 9</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/JetBrains/kotlin/commits">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-gradle-plugin&package-manager=gradle&previous-version=2.3.0&new-version=2.3.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>